# Generated by Django 2.2 on 2022-10-20 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Гараж',
                'verbose_name_plural': 'Гаражи',
            },
        ),
        migrations.CreateModel(
            name='GarageTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Наименование')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Garage', verbose_name='Гараж')),
            ],
            options={
                'verbose_name': 'Гаражный инструмент',
                'verbose_name_plural': 'Гаражный инструмент',
            },
        ),
    ]
