# Generated by Django 2.2 on 2022-10-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_garagestaff_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garagestaff',
            name='garage',
        ),
        migrations.RemoveField(
            model_name='garagestaff',
            name='person',
        ),
        migrations.RemoveField(
            model_name='garagetool',
            name='garage',
        ),
        migrations.DeleteModel(
            name='Garage',
        ),
        migrations.DeleteModel(
            name='GarageStaff',
        ),
        migrations.DeleteModel(
            name='GarageTool',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
